version: '3'
services:
  client:
    container_name: client
    image: client:latest
    entrypoint: python3 main.py
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - config
    volumes:
      - ./src:/src
      - ./safe_storage:/safe_storage
    network_mode: host
