version: '3'
services:
  client:
    container_name: client
    image: client:latest
    entrypoint: ../docker-entrypoint.sh
    command: python3 main.py
    environment:
      - FAKETIME_DONT_RESET=1
      - LD_PRELOAD=/usr/local/lib/faketime/libfaketime.so.1
      - PYTHONUNBUFFERED=1
    env_file:
      - config
    volumes:
      - ./src:/src
      - ./safe_storage:/safe_storage
    network_mode: host
